# 줄리아와 파이썬 비교

## 1. Basic

* 기본 함수

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 1,6], [7, 8, 1]])
print(A)

[[1 2 3]
 [4 1 6]
 [7 8 1]]


In [2]:
# 대각합
print(sum(np.diag(A)))

print(np.trace(A))

3
3


In [3]:
# 행렬식(determinant)
np.linalg.det(A)

103.99999999999999

In [4]:
np.linalg.inv(A)

array([[-0.45192308,  0.21153846,  0.08653846],
       [ 0.36538462, -0.19230769,  0.05769231],
       [ 0.24038462,  0.05769231, -0.06730769]])

In [5]:
A = np.array([[-4. , -17.], [2., 2.]])
print(A)

[[ -4. -17.]
 [  2.   2.]]


In [6]:
# 고유값 및 고유 벡터 

e, v = np.linalg.eig(A)

print(e)
print("--"*20)
print(v)

[-1.+5.j -1.-5.j]
----------------------------------------
[[ 0.9459053 +0.j          0.9459053 -0.j        ]
 [-0.16692447-0.27820744j -0.16692447+0.27820744j]]


* 행렬 분해

In [7]:
from scipy.linalg import lu

A = np.array([[1.5, 2, -4], [3, -1, -6], [-10, 2.3, 4]])
P, L, U = lu(A)
print(L, "\n"*3, U, "\n"*3)

[[ 1.          0.          0.        ]
 [-0.15        1.          0.        ]
 [-0.3        -0.13219616  1.        ]] 


 [[-10.           2.3          4.        ]
 [  0.           2.345       -3.4       ]
 [  0.           0.          -5.24946695]] 





In [8]:
from scipy.linalg import ldl

B = np.array([[1.5, 2, -4], [2, -1, -3], [-4, -3, 5]])

lu, d, perm = ldl(B, lower = True)

print(lu, "\n"*3, d, "\n"*3, perm)


[[-0.8         0.14285714  1.        ]
 [-0.6         1.          0.        ]
 [ 1.          0.          0.        ]] 


 [[ 5.          0.          0.        ]
 [ 0.         -2.8         0.        ]
 [ 0.          0.         -1.64285714]] 


 [2 1 0]


In [9]:
B = np.array([[1.5, 2, -4], [2, -1, -3], [-4, -3, 5]])

lu, d, perm = ldl(B, lower = False)

print(lu, "\n"*3, d, "\n"*3, perm)

[[ 1.          0.14285714 -0.8       ]
 [ 0.          1.         -0.6       ]
 [ 0.          0.          1.        ]] 


 [[-1.64285714  0.          0.        ]
 [ 0.         -2.8         0.        ]
 [ 0.          0.          5.        ]] 


 [0 1 2]


* 선형 해

In [10]:
x = [1, 2, 3]

In [11]:
# 선형 해 구하기
np.linalg.solve(B, x)

array([-1.73913043, -1.10869565, -1.45652174])

In [12]:
sol = np.linalg.solve(B, x)

In [13]:
np.matmul(B, sol)

array([1., 2., 3.])